AWSTemplateFormatVersion: "2010-09-09"
Description: VPC Stack
Resources:

    myInternetGateway:
        Type: AWS::EC2::InternetGateway
        Properties:
          Tags:
          - Key: stack
            Value: production

    myVPC:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: 10.0.0.0/16
        EnableDnsSupport: false
        EnableDnsHostnames: false
        InstanceTenancy: dedicated
        Tags:
        - Key: stack
          Value: production
      
      Type: AWS::EC2::VPCGatewayAttachment
      Properties: 
        InternetGatewayId: !Ref myInternetGateway
        VpcId: !Ref myVPC
